/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hackerrank.Day.Class.vs.Instance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
